name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
       lfs: true
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run screenshot tests with Gradle
      run: ./gradlew verifyPaparazziDebug
    - name: Run compose tests
      run: ./gradlew -Pandroid.experimental.androidTest.numManagedDeviceShards=5 -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=300 -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" pixel2api30DebugAndroidTest --warning-mode all "$@"
    - name: Zip build reports
      if: always()
      run: |
        shopt -s globstar
        zip buildreports.zip ./**/build/reports/**
    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: 'Build Reports'
        path: buildreports.zip
